### ISSUE TITLE
BluezonerIdGenerator::createBluezonerId is plainly wrong

### ISSUE THREAD

**Issue by sgn** [BluezoneGlobal/react-native-bluetooth-scan#6]
At first, I want to add this as a comment to either #2 or #5,

But, after some thought, I think this issue is different from both of them.

The Id generation is plainly wrong in those steps:

- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L25 `rand` is predictable, reported by #2 
- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L30 have you thought the consequence of the event `rand.nextLong()` returns `java.lang.Long.MIN_VALUE`? `Math.abs(java.lang.Long.MIN_VALUE)` will return `java.lang.Long.MIN_VALUE`, thus https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L33 will return (most likely) negative number, thus https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L36 will throw unchecked exception `StringIndexOutOfBoundsException`

```
$ cat BluezonerIdGenerator.java && javac BluezonerIdGenerator.java && java BluezonerIdGenerator
import java.util.Random;
public class BluezonerIdGenerator {
    public static String createBluezonerId(int numberChar) {
        final String charRandom = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        final int charRandomLength = charRandom.length();

        StringBuilder bluezonerIdBuilder = new StringBuilder();
        Random rand = new Random(System.currentTimeMillis());

        for (int i = 0;  i < numberChar; i++) {
            long randomValue = Math.abs(Long.MIN_VALUE);
            int index = (int) (randomValue % charRandomLength);
            bluezonerIdBuilder.append(charRandom.substring(index, index + 1));
        }
        return bluezonerIdBuilder.toString();
    }
    public static void main (String args[]) {
            BluezonerIdGenerator idGen = new BluezonerIdGenerator();
            System.out.println(idGen.createBluezonerId(6));
    }
}
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -8
        at java.lang.String.substring(String.java:1960)
        at BluezonerIdGenerator.createBluezonerId(BluezonerIdGenerator.java:13)
        at BluezonerIdGenerator.main(BluezonerIdGenerator.java:19)
```

- Next, even if `Random.nextLong()` doesn't return `Long.MIN_VALUE`, https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L30 causes the first bias to non-zero value, all non-zero values have a slightly higher priority to zero, (0 will be made from 0 only, 1 will be made from -1 and 1, and so on, etc...)
- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java#L33 creates more bias toward near index-0, this is discussed in #5, albeit, Huan only discussed about iOS.

---
UPDATE

- 2020-04-28T22:02:24: Correct LOC of last item,
- 2020-04-28T22:15:12: Correct LOC of `String::substring` and Exception's name.

**Comment by sgn** [comment]
Eh, my friends told me code without comment is bad, here is better version ;)
```
$ cat BluezonerIdGenerator.java
import java.util.Random;
public class BluezonerIdGenerator {
    public static String createBluezonerId(int numberChar) {
        final String charRandom = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        final int charRandomLength = charRandom.length();

        StringBuilder bluezonerIdBuilder = new StringBuilder();
        Random rand = new Random(System.currentTimeMillis());

        for (int i = 0;  i < numberChar; i++) {
            // Pretends that Random::nextLong() returns Long.MIN_VALUE
            // long randomValue = Math.abs(Random.nextLong());
            long randomValue = Math.abs(Long.MIN_VALUE);
            int index = (int) (randomValue % charRandomLength);
            bluezonerIdBuilder.append(charRandom.substring(index, index + 1));
        }
        return bluezonerIdBuilder.toString();
    }
    public static void main (String args[]) {
            BluezonerIdGenerator idGen = new BluezonerIdGenerator();
            System.out.println(idGen.createBluezonerId(6));
    }
}
$ javac BluezonerIdGenerator.java
$ java BluezonerIdGenerator
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -8
        at java.lang.String.substring(String.java:1960)
        at BluezonerIdGenerator.createBluezonerId(BluezonerIdGenerator.java:15)
        at BluezonerIdGenerator.main(BluezonerIdGenerator.java:21)
```

**Comment by sgn** [comment]
This may be a fix, but don't quote me on this:
```diff
diff --git a/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java b/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java
index 960b6de..d741580 100644
--- a/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java
+++ b/lib/android/src/main/java/com/scan/BluezonerIdGenerator.java
@@ -1,6 +1,6 @@
 package com.scan;
 
-import java.util.Random;
+import java.security.SecureRandom;
 
 /**
  * Class Create BluezonerId random
@@ -22,18 +22,15 @@ public class BluezonerIdGenerator {
         StringBuilder bluezonerIdBuilder = new StringBuilder();
         
         // Random
-        Random rand = new Random(System.currentTimeMillis());
+        SecureRandom rand = new SecureRandom();
 
         // for tao numberChar ki tu
         for (int i = 0;  i < numberChar; i++) {
-            // Check
-            long randomValue = Math.abs(rand.nextLong());
-
             // Index
-            int index = (int) (randomValue % charRandomLength);
+            int index = rand.nextInt(charRandomLength);
 
             // Create
-            bluezonerIdBuilder.append(charRandom.substring(index, index + 1));
+            bluezonerIdBuilder.append(charRandom.charAt(index));
         }
 
         // Ret
```

**Comment by khanguy00** [comment]
Or, as I mentioned in https://github.com/BluezoneGlobal/react-native-bluetooth-scan/issues/2#issuecomment-620505301

which is shorter and cover most of usages in this app.

**Comment by sgn** [comment]
> Or, as I mentioned in [#2 (comment)](https://github.com/BluezoneGlobal/react-native-bluetooth-scan/issues/2#issuecomment-620505301)
> 
> which is shorter and cover most of usages in this app.

I don't know much about Java, from its [documentation][*1*],
that looks like a better fix.

[*1*]: https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()
